version: '3.8'
services:
  db:
    extends:
      file: docker-compose.yml
      service: db
  coturn:
    extends:
      file: docker-compose.yml
      service: coturn
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
