version: '3.8'
services:
  db:
    image: mariadb:10-focal
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uyem_db
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
  coturn:
    image: instrumentisto/coturn
    network_mode: host
    container_name: turn
    restart: always
    volumes:
      - ./docs/resources/coturn.conf:/my/coturn.conf
    command: -c /my/coturn.conf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  nginx:
    image: nginx
    container_name: nginx
    network_mode: host
    restart: always
    volumes:
      - ./packages/client/build:/home/app/werift-sfu-react/packages/client/build
      - ./docs/resources/nginx.client.conf:/etc/nginx/conf.d/app.conf
