name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: nginx
        run: |
          sudo apt-get install nginx
          sudo cp docs/resources/nginx.client.conf /etc/nginx/conf.d/app.conf
          sudo systemctl restart nginx
      - name: application
        run: |
          docker-compose -f docker-compose.ci.yml up -d
          npm run env
          npm i
          which npm
      - name: build
        env:
          CI: false
        run: |
          npm run build
      - name: test
        env:
          CI: true
          NEXT: false
        run: |
          npm run test
