name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v1
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: prepare
        run: |
          sudo apt-get update
          sudo apt-get install libavdevice-dev libavfilter-dev libopus-dev libvpx-dev pkg-config libsrtp2-dev libasound2-dev -y
          sudo apt-get -y install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-pulseaudio
          npm i --omit=optional
      - name: test
        env:
          CI: true
      - name: build
        env:
          CI: true
        run: |
          npm run build
