name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get install libavdevice-dev libavfilter-dev libopus-dev libvpx-dev pkg-config libsrtp2-dev libasound2-dev -y
          sudo apt-get -y install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-pulseaudio
      - name: nginx
        run: |
          sudo apt-get install nginx
          sudo cp docs/resources/nginx.client.conf /etc/nginx/conf.d/app.conf
          sudo systemctl restart nginx
      - name: application
        run: |
          docker-compose up -d
          npm run env
          npm i
          which npm
      - name: build
        env:
          CI: false
        run: |
          npm run build
      - name: test
        env:
          CI: true
        run: |
          npm run test
